services:
  mysqldb:
    container_name: PrivatBank_MySQL
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: privat_bank
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PUBLIC_KEY: insecure_public_key